#!/bin/sh 
cd /usr/local/jenkins

LABELS="${LABELS:-docker}"
EXECUTORS="${EXECUTORS:-8}"
FSROOT="${FSROOT:-/tmp/jenkins}"
CREDENTIALS="${CREDENTIALS:--master $JENKINS_ADDR -username $JENKINS_USER -password $JENKINS_PASS}"

mkdir -p $FSROOT
java -jar slave.jar -labels $LABELS -executors $EXECUTORS -fsroot $FSROOT \
  -name docker-$(hostname) $CREDENTIALS
